table dates
	lineageTag: 7d8a1873-d788-4bc8-a409-8a35a7a18699

	column date_id
		dataType: int64
		formatString: 0
		lineageTag: 12d9b5e4-5804-49a3-8b25-d8fdf37c2cfc
		summarizeBy: none
		sourceColumn: date_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d93a13b0-be55-43cb-ac21-8ad7ca335609
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 35d7dd53-5c53-4ee0-b49b-0f7e1c1cd887
			defaultHierarchy: LocalDateTable_8334bc27-3099-46d0-a080-9aa96b787607.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column date_month
		dataType: int64
		formatString: 0
		lineageTag: 9203a04b-cead-4d85-b987-60b4c889663b
		summarizeBy: sum
		sourceColumn: date_month

		annotation SummarizationSetBy = Automatic

	column date_day
		dataType: int64
		formatString: 0
		lineageTag: c0a25f0c-76ed-491b-a206-fc3cad4ef343
		summarizeBy: sum
		sourceColumn: date_day

		annotation SummarizationSetBy = Automatic

	column date_weekday
		dataType: string
		lineageTag: 5ebb127f-bf52-4cc8-8670-7c2399b9078f
		summarizeBy: none
		sourceColumn: date_weekday

		annotation SummarizationSetBy = Automatic

	column date_week
		dataType: int64
		formatString: 0
		lineageTag: 42f8a287-f890-475c-a564-a89c27876bd1
		summarizeBy: sum
		sourceColumn: date_week

		annotation SummarizationSetBy = Automatic

	partition dates = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Lukas Schaub\Desktop\eshop_dashboard\dates.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date_id", Int64.Type}, {"date", type date}, {"date_month", Int64.Type}, {"date_day", Int64.Type}, {"date_weekday", type text}, {"date_week", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

