table sales
	lineageTag: 66524d68-64f8-4d94-aa4c-5eb206965abc

	measure total_revenue = SUM(sales[discounted_price])
		lineageTag: fab20512-8ddf-4e05-8b64-d493a52c69fa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure total_units_sold = SUM(sales[sale_quantity])
		formatString: 0
		lineageTag: f71b156a-32ea-4308-a995-0adcdc1f031e

	measure discounted_revenue = SUMX(sales, sales[sale_quantity] * sales[discounted_price])
		lineageTag: 37fc12b0-8cec-49c4-8f54-35d2e64d66ea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure revenue_in_feb =
			CALCULATE(
			    [discounted_revenue],
			    DATESINPERIOD(dates[date], DATE(2025, 2, 1), 27, DAY)
			)
		lineageTag: c6da1041-8092-4eaa-94bd-328d8a6d75bf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: 9917311d-cf80-47b0-a437-e760958b1626
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date_id
		dataType: int64
		formatString: 0
		lineageTag: f5ebd7a9-98f2-425b-b5bb-06ae344746d9
		summarizeBy: none
		sourceColumn: date_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: bdfdd8bd-4757-4377-860a-b68c2ce00c7d
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: 00c5c31c-52a0-49bf-b83c-de3b757271b7
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column store_id
		dataType: int64
		formatString: 0
		lineageTag: ffda0ff0-aeba-4bff-8fb2-d408c2f3d548
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column sale_quantity
		dataType: int64
		formatString: 0
		lineageTag: 9141332f-f496-4cdc-9535-2cd20ebf8143
		summarizeBy: sum
		sourceColumn: sale_quantity

		annotation SummarizationSetBy = Automatic

	column sale_discount
		dataType: double
		lineageTag: 92acec2c-5590-440a-94d8-66d37c72b61d
		summarizeBy: sum
		sourceColumn: sale_discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column price = sales[sale_quantity] * RELATED(products[product_list_price])
		lineageTag: bb00adc3-163d-46e2-a94c-3148ee399ca9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column discounted_price = sales[price]*(1-sales[sale_discount])
		lineageTag: bd48f04c-2dde-438d-b01f-fbc01ffff1b3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bulk_order = IF(sales[sale_quantity] > 3, True(), False())
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b739424b-e37e-441e-b62e-5ef2918ec789
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column order_size =
			SWITCH(
			    TRUE,
			    sales[discounted_price] < 100, "Tiny",
			    sales[discounted_price] < 200, "Mid",
			    "Massive"
			)
		lineageTag: 7f5a4218-6428-4874-b727-ab2b9770d2f0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Lukas Schaub\Desktop\eshop_dashboard\sales.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date_id", Int64.Type}, {"customer_id", Int64.Type}, {"product_id", Int64.Type}, {"store_id", Int64.Type}, {"sale_quantity", Int64.Type}, {"sale_discount", type number}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"sale_id"})
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

