table sales
	lineageTag: 66524d68-64f8-4d94-aa4c-5eb206965abc

	measure total_revenue = SUM(sales[discounted_price])
		lineageTag: fab20512-8ddf-4e05-8b64-d493a52c69fa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: 9917311d-cf80-47b0-a437-e760958b1626
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date_id
		dataType: int64
		formatString: 0
		lineageTag: f5ebd7a9-98f2-425b-b5bb-06ae344746d9
		summarizeBy: none
		sourceColumn: date_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: bdfdd8bd-4757-4377-860a-b68c2ce00c7d
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: 00c5c31c-52a0-49bf-b83c-de3b757271b7
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column store_id
		dataType: int64
		formatString: 0
		lineageTag: ffda0ff0-aeba-4bff-8fb2-d408c2f3d548
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column sale_quantity
		dataType: int64
		formatString: 0
		lineageTag: 9141332f-f496-4cdc-9535-2cd20ebf8143
		summarizeBy: sum
		sourceColumn: sale_quantity

		annotation SummarizationSetBy = Automatic

	column sale_discount
		dataType: double
		lineageTag: 92acec2c-5590-440a-94d8-66d37c72b61d
		summarizeBy: sum
		sourceColumn: sale_discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column price = sales[sale_quantity] * RELATED(products[product_list_price])
		lineageTag: bb00adc3-163d-46e2-a94c-3148ee399ca9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column discounted_price = sales[price]*(1-sales[sale_discount])
		lineageTag: bd48f04c-2dde-438d-b01f-fbc01ffff1b3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Lukas Schaub\Desktop\eshop_dashboard\sales.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date_id", Int64.Type}, {"customer_id", Int64.Type}, {"product_id", Int64.Type}, {"store_id", Int64.Type}, {"sale_quantity", Int64.Type}, {"sale_discount", type number}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"sale_id"})
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

